### PR TITLE
Bugfix/issue-140 broken record and verify tasks on windows

### LINKED ISSUE #140: Can not pull record screenshots from the phone to the project on Windows 10
### Expected behaviour
Run command to record screenshots and get recorded screenshots in images/recorded folder and screenshots folder in the project on Windows 10

### Actual behaviour
I didn't see recorded screenshots in my project although terminal of Android Studio notify pulling screenshots successfully

### Steps to reproduce
1. Run the command on Windows 10: gradlew mockWebServerMobileNativeDebugExecuteScreenshotTests -Precord -Pandroid.testInstrumentationRunnerArguments.class=my_testcase.
2. Terminal of Android Studio notice that task done successfully.
image
3. The images/record folder doesn't contain record screenshots as my expectation.
image
The screenshots folder also doesn't contains the record screenshots.
### Version of the library
4.3.0, 4.4.0

* I used Gradle 5.4.1.
* On MacOS 10.15.6, I can run record screenshots command and get the record screenshots.

### PR DESCRIPTION
**Pull request by mariuszmarzec**
### :pushpin: References
* **Issue:** Closes #140

### :tophat: What is the goal?

Verify and record tasks are broken on Windows due to hardcoded unix tmp dir and unix style metadata path returned by `Config.metadataFileName` method.

### How is it being implemented?

Replaced system tmp dir with tmp dir from build directory.

### How can it be tested?

Added unit tests, tested locally on Windows

- [x] **Use case 1:** _Unit tests passed_
  - [x] _Step 1_ `gradlew core:test`

### CODE REVIEW

**Comment by mariuszmarzec** [comment]
@pedrovgs Ready to check :)

**Comment by pedrovgs** [comment]
Hey @mariuszmarzec thank you so much for your contribution. I've merged a previous one that generates conflicts with yours because now the folder path is computed inside a data class improving a lot the quality of the code. Could you please update this PR? You can even move the OS param to the new ``ShotFolder`` data class and implement the fix there. This would simplify a lot your changes.

**Comment by mariuszmarzec** [comment]
@pedrovgs I changed slightly approach to fix this issue. 
Fact one, after merged PR with shot folder, it is not necessary to:

> Changed metadataFileName to metadataFilePath. Added new metadataFileName which returns only metadata.xml file name.

And second thing. After some thoughts i decided to not introduce dependency on system. Instead of i suggest to not use tmp system dir, we could use `build/tmp' path.

**Review by pedrovgs — APPROVED** [review]
The code looks awesome now. Thank you so much @mariuszmarzec. I'm wondering if we could configure CI to check if the windows build is working automatically for us. I'm going to ask for a second check on the original issue too before merging the PR and releasing a new version 😃

**Comment by pedrovgs** [comment]
@mariuszmarzec can you fix the code formatting? You can do it just running ``./gradlew scalaFmtAll`` and then commit the changes 😃  Thank you!

**Comment by mariuszmarzec** [comment]
@pedrovgs Now should be fine, i tried `./gradlew scalaFmtAll` before but it made mess with changing LF into CRLF and i decided to reformat files in different way. This time i better checked what reallly need to be changed with scalaFmt 😄

**Comment by mariuszmarzec** [comment]
@pedrovgs I have checked locally and only first one is failing on my machine and it is connected with keyboard.
```
12-08 13:43:53.492 20316 20341 E TestRunner: failed: cursorIsNotVisibleOnScreenshot(com.karumi.ui.view.CursorActivityTest)
12-08 13:43:53.492 20316 20341 E TestRunner: ----- begin exception -----
12-08 13:43:53.492 20316 20341 E TestRunner: java.lang.IllegalStateException: We couldn't close they keyboard after 5 retries.
12-08 13:43:53.492 20316 20341 E TestRunner: at com.karumi.shot.KeyboardCloser$DefaultImpls.recursiveCloseKeyboardAndWaitUntilIsNotVisible(KeyboardCloser.kt:30)
```

**Pull request merged**
